//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongGym.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int IDHD { get; set; }
        public int IDKH { get; set; }
        public Nullable<int> IDGT { get; set; }
        public Nullable<int> IDLT { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual GoiTap GoiTap { get; set; }
        public virtual LichThueHLV LichThueHLV { get; set; }
        public virtual User User { get; set; }
    }
}
