//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongGym.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichThueHLV
    {
        public int IDLT { get; set; }
        public int IDHLV { get; set; }
        public Nullable<int> IDCa { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public int IDKH { get; set; }
    
        public virtual User HLVs { get; set; }
        public virtual User KHs { get; set; }
    }
}
