//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongGym.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViecTrongTuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichLamViecTrongTuan()
        {
            this.TinhTrangLamViecHLVs = new HashSet<TinhTrangLamViecHLV>();
        }
    
        public int IDLLV { get; set; }
        public Nullable<int> IDHLV { get; set; }
        public Nullable<int> IDCa { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayLam { get; set; }
    
        public virtual CaLamViec CaLamViec { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinhTrangLamViecHLV> TinhTrangLamViecHLVs { get; set; }
    }
}
