
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QLPhongGym.DTO
{

using System;
    using System.Collections.Generic;
    
public partial class ThietBi
{

    public int IDTB { get; set; }

    public Nullable<int> IDBT { get; set; }

    public string Name { get; set; }

    public string TrangThai { get; set; }

    public byte[] Image { get; set; }

    public Nullable<int> SoLuong { get; set; }



    public virtual BaiTap BaiTap { get; set; }

}

}
