//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongGym.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public int IDTB { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> SoLuongHong { get; set; }
        public string NhaCungCap { get; set; }
        public string MoTa { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> NamSX { get; set; }
    }
}
