//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPhongGym.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinhTrangHLV
    {
        public int IDHLV { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<int> SoNgayLam { get; set; }
        public Nullable<double> DanhGia { get; set; }
    
        public virtual User User { get; set; }
    }
}
